from models import Asset, Risk, Threat, Vulnerability, db


def seed_database(app):
    with app.app_context():
        if Asset.query.first():
            return  # Database already seeded

        assets = [
            Asset(
                name="Production Database Server",
                asset_type="Server",
                owner="IT Team",
                criticality=5,
            ),
            Asset(
                name="Source Code Repository",
                asset_type="Application",
                owner="Dev Team",
                criticality=5,
            ),
            Asset(
                name="Employee Workstations",
                asset_type="Workstation",
                owner="IT Team",
                criticality=3,
            ),
            Asset(
                name="Company Email System",
                asset_type="Application",
                owner="IT Team",
                criticality=4,
            ),
            Asset(
                name="Customer Data Storage",
                asset_type="Data",
                owner="IT Team",
                criticality=5,
            ),
            Asset(
                name="Internal Wi-Fi Network",
                asset_type="Network",
                owner="IT Team",
                criticality=3,
            ),
            Asset(
                name="CI/CD Pipeline",
                asset_type="Application",
                owner="Dev Team",
                criticality=4,
            ),
            Asset(
                name="Cloud VPS Instances",
                asset_type="Server",
                owner="DevOps Team",
                criticality=4,
            ),
            Asset(
                name="Employee Personal Devices (BYOD)",
                asset_type="Workstation",
                owner="HR Department",
                criticality=2,
            ),
            Asset(
                name="Office Physical Access System",
                asset_type="Physical",
                owner="Admin Team",
                criticality=3,
            ),
        ]
        db.session.add_all(assets)
        db.session.commit()

        threats = [
            Threat(name="Ransomware Attack", category="Malware"),
            Threat(name="Phishing Campaign", category="Social Engineering"),
            Threat(name="SQL Injection Attack", category="Network Attack"),
            Threat(name="DDoS Attack", category="Network Attack"),
            Threat(name="Insider Data Theft", category="Insider Threat"),
            Threat(name="Brute Force Authentication", category="Network Attack"),
            Threat(name="Supply Chain Compromise", category="Malware"),
            Threat(name="Social Engineering via Phone", category="Social Engineering"),
            Threat(name="Physical Break-in", category="Physical"),
            Threat(name="Zero-day Exploit", category="Malware"),
            Threat(name="Man-in-the-Middle Attack", category="Network Attack"),
            Threat(name="Accidental Data Deletion", category="Insider Threat"),
        ]
        db.session.add_all(threats)
        db.session.commit()

        vulnerabilities = [
            Vulnerability(
                name="Unpatched Operating Systems",
                severity="High",
                cve_id="CVE-2024-21351",
            ),
            Vulnerability(name="Weak Password Policy", severity="Medium"),
            Vulnerability(name="No Multi-Factor Authentication", severity="High"),
            Vulnerability(
                name="Outdated Third-Party Libraries",
                severity="High",
                cve_id="CVE-2024-3094",
            ),
            Vulnerability(name="Missing Data Encryption at Rest", severity="Medium"),
            Vulnerability(name="No Network Segmentation", severity="Medium"),
            Vulnerability(
                name="Insufficient Logging and Monitoring", severity="Medium"
            ),
            Vulnerability(
                name="Missing Input Validation",
                severity="High",
                cve_id="CVE-2023-44487",
            ),
            Vulnerability(name="No Employee Security Training", severity="Medium"),
            Vulnerability(name="Unencrypted Backup Storage", severity="High"),
            Vulnerability(name="Open Unnecessary Ports", severity="Medium"),
            Vulnerability(name="No Rate Limiting on APIs", severity="Low"),
        ]
        db.session.add_all(vulnerabilities)
        db.session.commit()

        risks_data = [
            # Critical Risks (score >= 20)
            {
                "name": "Ransomware encrypts Production Database due to unpatched OS",
                "a": 0,
                "t": 0,
                "v": 0,
                "l": 5,
                "i": 5,
                "o": "CTO",
                "s": "Open",
                "m": "Patch OS and implement EDR",
            },
            {
                "name": "Customer data stolen via SQL injection",
                "a": 4,
                "t": 2,
                "v": 7,
                "l": 4,
                "i": 5,
                "o": "Security Officer",
                "s": "Open",
                "m": "Implement WAF and fix input validation",
            },
            {
                "name": "CI/CD Pipeline compromised via supply chain",
                "a": 6,
                "t": 6,
                "v": 3,
                "l": 4,
                "i": 5,
                "o": "DevOps Lead",
                "s": "Mitigating",
                "m": "Update libraries, scan dependencies",
            },
            # High Risks (score 12-19)
            {
                "name": "Phishing leads to email system access",
                "a": 3,
                "t": 1,
                "v": 2,
                "l": 4,
                "i": 4,
                "o": "IT Manager",
                "s": "Mitigating",
                "m": "Enable MFA and training",
            },
            {
                "name": "Insider steals source code",
                "a": 1,
                "t": 4,
                "v": 6,
                "l": 3,
                "i": 5,
                "o": "CTO",
                "s": "Open",
                "m": "Implement DLP and monitor access",
            },
            {
                "name": "Cloud VPS breached via brute force",
                "a": 7,
                "t": 5,
                "v": 1,
                "l": 4,
                "i": 3,
                "o": "DevOps Lead",
                "s": "Closed",
                "m": "Enforce strong passwords",
            },
            {
                "name": "Zero-day exploit on Database Server",
                "a": 0,
                "t": 9,
                "v": 6,
                "l": 3,
                "i": 5,
                "o": "Security Officer",
                "s": "Open",
                "m": "Deploy network segmentation",
            },
            {
                "name": "DDoS takes down Customer Data Storage access",
                "a": 4,
                "t": 3,
                "v": 6,
                "l": 3,
                "i": 4,
                "o": "IT Manager",
                "s": "Accepted",
                "m": "Accepting risk for now due to cost",
            },
            # Medium Risks (score 5-11)
            {
                "name": "Data deletion on Employee Workstation",
                "a": 2,
                "t": 11,
                "v": 9,
                "l": 3,
                "i": 3,
                "o": "IT Manager",
                "s": "Open",
                "m": "Implement regular backups",
            },
            {
                "name": "Physical break-in to Office",
                "a": 9,
                "t": 8,
                "v": 8,
                "l": 2,
                "i": 4,
                "o": "Admin Team",
                "s": "Open",
                "m": "Install security cameras",
            },
            {
                "name": "Phone social engineering to reset passwords",
                "a": 3,
                "t": 7,
                "v": 8,
                "l": 3,
                "i": 3,
                "o": "HR Manager",
                "s": "Mitigating",
                "m": "Training on verification",
            },
            {
                "name": "Man-in-the-Middle on Internal Wi-Fi",
                "a": 5,
                "t": 10,
                "v": 5,
                "l": 2,
                "i": 3,
                "o": "IT Manager",
                "s": "Open",
                "m": "Segment network",
            },
            {
                "name": "BYOD malware infection",
                "a": 8,
                "t": 0,
                "v": 1,
                "l": 4,
                "i": 2,
                "o": "HR Manager",
                "s": "Closed",
                "m": "Deployed MDM solution",
            },
            {
                "name": "Data exposure on unencrypted backup",
                "a": 4,
                "t": 4,
                "v": 9,
                "l": 2,
                "i": 5,
                "o": "CTO",
                "s": "Open",
                "m": "Encrypt backups",
            },
            {
                "name": "Excessive API usage leading to partial outage",
                "a": 6,
                "t": 3,
                "v": 11,
                "l": 5,
                "i": 2,
                "o": "DevOps Lead",
                "s": "Mitigating",
                "m": "Implement rate limiting",
            },
            # Low Risks (score 1-4)
            {
                "name": "Unnecessary open ports scanned",
                "a": 7,
                "t": 3,
                "v": 10,
                "l": 3,
                "i": 1,
                "o": "DevOps Lead",
                "s": "Accepted",
                "m": "Monitor logs",
            },
            {
                "name": "Accidental deletion of non-critical documents",
                "a": 2,
                "t": 11,
                "v": 8,
                "l": 2,
                "i": 1,
                "o": "HR Manager",
                "s": "Accepted",
                "m": "None",
            },
            {
                "name": "Shoulder surfing at coffee shop",
                "a": 8,
                "t": 8,
                "v": 8,
                "l": 2,
                "i": 2,
                "o": "HR Manager",
                "s": "Open",
                "m": "Provide privacy screens",
            },
            {
                "name": "Minor phishing attempt on old domain",
                "a": 3,
                "t": 1,
                "v": 8,
                "l": 1,
                "i": 1,
                "o": "IT Manager",
                "s": "Closed",
                "m": "Domain blocklisted",
            },
            {
                "name": "Brute force on internal low-privilege system",
                "a": 5,
                "t": 5,
                "v": 1,
                "l": 2,
                "i": 1,
                "o": "IT Manager",
                "s": "Accepted",
                "m": "Monitor attempts",
            },
            {
                "name": "Physical theft of older laptop",
                "a": 2,
                "t": 8,
                "v": 4,
                "l": 1,
                "i": 3,
                "o": "IT Manager",
                "s": "Mitigating",
                "m": "Ensure disk encryption",
            },
            {
                "name": "Low-level API abuse",
                "a": 6,
                "t": 3,
                "v": 11,
                "l": 2,
                "i": 2,
                "o": "DevOps Lead",
                "s": "Accepted",
                "m": "No action needed currently",
            },
        ]

        for data in risks_data:
            r = Risk(
                risk_name=data["name"],
                asset_id=assets[data["a"]].id,
                threat_id=threats[data["t"]].id,
                vulnerability_id=vulnerabilities[data["v"]].id,
                likelihood=data["l"],
                impact=data["i"],
                owner=data["o"],
                status=data["s"],
                mitigation=data["m"],
            )
            db.session.add(r)

        db.session.commit()
